const coursesData = [
    {
        id: 1,
        title: "Классическая механика",
        instructor: "Проф. Александр Петров",
        price: 5999,
        oldPrice: 9999,
        level: "beginner",
        levelName: "Начальный",
        subject: "physics",
        subjectName: "Физика",
        rating: 4.8,
        reviews: 342,
        students: 1856,
        duration: "32 часа",
        lessons: 48,
        image: "images/courses/course-1.png",
        description: "Основы классической механики: законы Ньютона, кинематика, динамика.",
        whatYouLearn: [
            "Законы Ньютона и их применение",
            "Кинематика и динамика",
            "Законы сохранения",
            "Колебания и волны"
        ],
        videoId: "w1iV7z14Dv0"
    },
    {
        id: 2,
        title: "Введение в машинное обучение",
        instructor: "Д-р Елена Сидорова",
        price: 8999,
        oldPrice: 14999,
        level: "beginner",
        levelName: "Начальный",
        subject: "ai",
        subjectName: "Искусственный интеллект",
        rating: 4.9,
        reviews: 567,
        students: 3245,
        duration: "40 часов",
        lessons: 62,
        image: "images/courses/course-2.png",
        description: "Основы машинного обучения: от линейной регрессии до нейронных сетей.",
        whatYouLearn: [
            "Основы ML и типы обучения",
            "Линейная и логистическая регрессия",
            "Деревья решений и ансамбли",
            "Введение в нейронные сети"
        ],
        videoId: "cNdzu5F6LV8"
    },
    {
        id: 3,
        title: "Квантовая механика для начинающих",
        instructor: "Проф. Михаил Козлов",
        price: 7499,
        oldPrice: 12999,
        level: "intermediate",
        levelName: "Средний",
        subject: "physics",
        subjectName: "Физика",
        rating: 4.7,
        reviews: 234,
        students: 1123,
        duration: "36 часов",
        lessons: 54,
        image: "images/courses/course-3.png",
        description: "Погружение в мир квантовой физики: от основ до квантовых вычислений.",
        whatYouLearn: [
            "Волновая функция и уравнение Шрёдингера",
            "Квантовый гармонический осциллятор",
            "Момент импульса и спин",
            "Основы квантовых вычислений"
        ],
        videoId: "p7bzE1E5PMY"
    },
    {
        id: 4,
        title: "Нейронные сети и глубокое обучение",
        instructor: "Д-р Анна Морозова",
        price: 9999,
        oldPrice: 16999,
        level: "intermediate",
        levelName: "Средний",
        subject: "ai",
        subjectName: "Искусственный интеллект",
        rating: 4.9,
        reviews: 489,
        students: 2678,
        duration: "48 часов",
        lessons: 72,
        image: "images/courses/course-4.png",
        description: "Современные архитектуры нейронных сетей: CNN, RNN, Transformers.",
        whatYouLearn: [
            "Перцептрон и backpropagation",
            "Свёрточные нейросети (CNN)",
            "Рекуррентные сети (RNN, LSTM)",
            "Трансформеры и attention"
        ],
        videoId: "sHnmnEH1Pj0"
    },
    {
        id: 5,
        title: "Электромагнетизм и электродинамика",
        instructor: "Проф. Сергей Волков",
        price: 6999,
        oldPrice: 11999,
        level: "intermediate",
        levelName: "Средний",
        subject: "physics",
        subjectName: "Физика",
        rating: 4.6,
        reviews: 198,
        students: 945,
        duration: "34 часа",
        lessons: 50,
        image: "images/courses/course-5.png",
        description: "Уравнения Максвелла, электромагнитные волны и их применение.",
        whatYouLearn: [
            "Электростатика и закон Кулона",
            "Магнитное поле и закон Ампера",
            "Уравнения Максвелла",
            "Электромагнитные волны"
        ],
        videoId: "X1reqWft42g"
    },
    {
        id: 6,
        title: "Обработка естественного языка (NLP)",
        instructor: "Д-р Дмитрий Новиков",
        price: 8499,
        oldPrice: 13999,
        level: "advanced",
        levelName: "Продвинутый",
        subject: "ai",
        subjectName: "Искусственный интеллект",
        rating: 4.8,
        reviews: 312,
        students: 1567,
        duration: "42 часа",
        lessons: 64,
        image: "images/courses/course-6.png",
        description: "Современные методы NLP: от токенизации до BERT и GPT.",
        whatYouLearn: [
            "Токенизация и векторизация текста",
            "Word embeddings (Word2Vec, GloVe)",
            "Трансформеры и BERT",
            "GPT и генерация текста"
        ],
        videoId: "fNxaJsNG3-s"
    },
    {
        id: 7,
        title: "Термодинамика и статистическая физика",
        instructor: "Проф. Ольга Иванова",
        price: 6499,
        oldPrice: 10999,
        level: "intermediate",
        levelName: "Средний",
        subject: "physics",
        subjectName: "Физика",
        rating: 4.7,
        reviews: 176,
        students: 834,
        duration: "30 часов",
        lessons: 45,
        image: "images/courses/course-7.png",
        description: "Законы термодинамики, статистические ансамбли и фазовые переходы.",
        whatYouLearn: [
            "Законы термодинамики",
            "Термодинамические потенциалы",
            "Статистические ансамбли",
            "Фазовые переходы"
        ],
        videoId: "3QfFH0jjTxs"
    },
    {
        id: 8,
        title: "Компьютерное зрение (Computer Vision)",
        instructor: "Д-р Максим Лебедев",
        price: 9499,
        oldPrice: 15999,
        level: "advanced",
        levelName: "Продвинутый",
        subject: "ai",
        subjectName: "Искусственный интеллект",
        rating: 4.9,
        reviews: 423,
        students: 2134,
        duration: "46 часов",
        lessons: 68,
        image: "images/courses/course-8.png",
        description: "Современные методы анализа изображений: от детекции до сегментации.",
        whatYouLearn: [
            "Обработка изображений и фильтры",
            "Детекция объектов (YOLO, R-CNN)",
            "Семантическая сегментация",
            "GAN и генерация изображений"
        ],
        videoId: "nDPWyvWRIRo"
    },
    {
        id: 9,
        title: "Теория относительности",
        instructor: "Проф. Наталья Соколова",
        price: 7999,
        oldPrice: 13999,
        level: "advanced",
        levelName: "Продвинутый",
        subject: "physics",
        subjectName: "Физика",
        rating: 4.8,
        reviews: 267,
        students: 1045,
        duration: "38 часов",
        lessons: 56,
        image: "images/courses/course-9.png",
        description: "Специальная и общая теория относительности Эйнштейна.",
        whatYouLearn: [
            "Принципы специальной теории относительности",
            "Пространство-время Минковского",
            "Общая теория относительности",
            "Чёрные дыры и гравитационные волны"
        ],
        videoId: "qJnLsOZhUaw"
    },
    {
        id: 10,
        title: "Обучение с подкреплением (Reinforcement Learning)",
        instructor: "Д-р Андрей Орлов",
        price: 10999,
        oldPrice: 17999,
        level: "advanced",
        levelName: "Продвинутый",
        subject: "ai",
        subjectName: "Искусственный интеллект",
        rating: 4.9,
        reviews: 345,
        students: 1678,
        duration: "50 часов",
        lessons: 75,
        image: "images/courses/course-10.png",
        description: "Алгоритмы RL: от Q-learning до Deep Q-Networks и Policy Gradients.",
        whatYouLearn: [
            "Марковские процессы принятия решений",
            "Q-learning и SARSA",
            "Deep Q-Networks (DQN)",
            "Policy Gradients и Actor-Critic"
        ],
        videoId: "qv6UVOQ0F44"
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { coursesData };
}